services:
  - type: web
    name: mern-portfolio-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: HF_ACCESS_TOKEN
        sync: false
