name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REACT_APP_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: |
        cd client
        npm install

    - name: Build
      run: |
        cd client
        REACT_APP_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} npm run build

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      env:
        REACT_APP_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # Add your deployment steps here
